jobs: 4
matrix:
  - name: Markdown
    aspell: 
      lang: it_IT
    dictionary:
      encoding: utf-8
    pipeline:
      - pyspelling.filters.markdown:
    sources:
      - 'docs/*.md'
    default_encoding: utf-8
