name: Build and Release Sprint Fat Jar and Documentation

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:

  build-and-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'sbt'

      - name: Build Fat Jar
        run: sbt clean assembly

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: scala-game-executable
          path: target/scala-*/your-game-assembly-*.jar

      - name: Release to GitHub
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/scala-*/your-game-assembly-*.jar
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}